// The single place an engagement's stage changes from application code
// (section 10's worked example: "Candidate submitted -> create client
// feedback SLA. Client says yes -> create interview scheduling SLA.
// Interview completed -> create candidate debrief + client feedback
// actions. Offer accepted -> create start-date and invoice readiness
// actions."). Every caller -- the pipeline UI, the DCT, a future
// interview-completion action -- goes through transitionEngagementStage()
// so the stage/history/task/event/audit relationship can't drift out of
// sync between call sites the way the old pipeline-table stalled-flag bug
// did between the KPI query and the table row.
import { eq } from "drizzle-orm";
import { withActor, type Actor, type DbTx } from "@/db/client";
import { engagement, task } from "@/db/schema";
import type { EngagementStage } from "./stages";
import { slaDueDate, type SlaZone } from "./sla";
import { writeEvent } from "@/events/writer";
import { writeAuditLog } from "@/audit/log";

type AutoTaskRule = {
  type: string;
  category: "client_follow_up" | "candidate_follow_up" | "interview" | "offer" | "finance";
  slaZone?: SlaZone;
  dueInDays?: number; // calendar days, for rules that aren't one of the four formal SLA zones
  assignToOwner: boolean;
};

// The stage-transition -> auto-task map. Keyed by the stage being ENTERED
// (not left) -- entering 'submitted' opens the client-feedback clock,
// entering 'client_process' opens the interview-scheduling clock, etc.
// Multiple rules can fire for one transition (offer acceptance opens both
// a start-date task and an invoice-readiness task).
const AUTO_TASK_RULES: Partial<Record<EngagementStage, AutoTaskRule[]>> = {
  submitted: [
    { type: "Get client feedback on submittal", category: "client_follow_up", slaZone: "submittal_to_feedback", assignToOwner: true },
  ],
  client_process: [
    { type: "Schedule first interview", category: "interview", slaZone: "yes_to_interview", assignToOwner: true },
  ],
  offer: [
    { type: "Confirm offer acceptance", category: "offer", dueInDays: 3, assignToOwner: true },
  ],
  pending_start: [
    { type: "Confirm start date", category: "offer", dueInDays: 5, assignToOwner: true },
    { type: "Prepare invoice for placement", category: "finance", dueInDays: 2, assignToOwner: false },
  ],
};

async function createAutoTasks(
  tx: DbTx,
  engagementId: string,
  ownerUserId: string | null,
  rules: AutoTaskRule[],
): Promise<void> {
  for (const rule of rules) {
    const dueAt = rule.slaZone ? slaDueDate(rule.slaZone) : rule.dueInDays ? addDays(new Date(), rule.dueInDays) : undefined;
    await tx.insert(task).values({
      engagementId,
      entityType: "engagement",
      entityId: engagementId,
      type: rule.type,
      taskKind: "system_generated",
      category: rule.category,
      slaZone: rule.slaZone,
      assigneeUserId: rule.assignToOwner ? ownerUserId ?? undefined : undefined,
      dueAt,
      autoGenerated: true,
    });
  }
}

function addDays(from: Date, days: number): Date {
  const d = new Date(from);
  d.setDate(d.getDate() + days);
  return d;
}

export type TransitionResult = { engagementId: string; fromStage: string; toStage: EngagementStage; tasksCreated: number };

export async function transitionEngagementStage(
  engagementId: string,
  toStage: EngagementStage,
  actor: Actor,
  reason?: string,
): Promise<TransitionResult> {
  return withActor(actor, async (tx) => {
    const [before] = await tx.select().from(engagement).where(eq(engagement.id, engagementId)).limit(1);
    if (!before) throw new Error("engagement not found");

    const fromStage = before.currentStage;

    // The UPDATE itself fires engagement_record_stage_change (migrations/
    // 0010), which writes engagement_stage_history and resets
    // stage_entered_at -- neither is done here in application code, so
    // there's exactly one place either can happen, ever.
    await tx.update(engagement).set({ currentStage: toStage }).where(eq(engagement.id, engagementId));

    const rules = AUTO_TASK_RULES[toStage] ?? [];
    if (rules.length > 0) {
      await createAutoTasks(tx, engagementId, before.ownerUserId, rules);
    }

    await writeEvent(tx, {
      type: "engagement.stage_changed",
      source: "manual_ui",
      entityType: "engagement",
      entityId: engagementId,
      payload: { fromStage, toStage, reason },
      occurredAt: new Date(),
    });

    await writeAuditLog(tx, {
      actorUserId: actor.userId,
      action: "transition_stage",
      entityType: "engagement",
      entityId: engagementId,
      before: { stage: fromStage },
      after: { stage: toStage, reason },
    });

    return { engagementId, fromStage, toStage, tasksCreated: rules.length };
  });
}

// Interview-completion side effects (section 10's third example): candidate
// debrief + client feedback tasks. Called by the Interviews module when a
// scheduled interview is marked completed -- not folded into
// transitionEngagementStage() because completing an interview doesn't by
// itself change the engagement's stage (a recruiter still decides whether
// that means "next round" or "client_process continues").
export async function createInterviewCompletionTasks(
  tx: DbTx,
  engagementId: string,
  ownerUserId: string | null,
): Promise<void> {
  await createAutoTasks(tx, engagementId, ownerUserId, [
    { type: "Debrief candidate on interview", category: "candidate_follow_up", slaZone: "interview_to_feedback", assignToOwner: true },
    { type: "Get client feedback on interview", category: "client_follow_up", slaZone: "interview_to_feedback", assignToOwner: true },
  ]);
}
